---
- hosts: all
  tasks:
  - name: create a group developers
    group:
      name: developers
      state: present

  - name: create a user
    user: 
     name: "dev1"
     state: present
     shell: /bin/bash
     create_home: true
     groups: developers

